### ISSUE TITLE
Add transition between the input videos

### ISSUE THREAD

**Issue by rahul799** [salaheddinek/video-editing-py-script#10]
Right now, when I execute 

`vid_transition.py -i ex_vid1.mp4  ex_vid2.mp4 --animation translation --num_frames 15 --max_brightness 1.5` 
I get two video output **vt1_phase.mp4** & **vt2_phase.mp4**.

But I want a single video let's say output.mp4 that will basically merge the two input videos and will add the transition between the joint of the first and second video.

**Comment by salaheddinek** [comment]
I will add an option to produce one video transition that contains the two phases, instead of two separate video chunks.

**Comment by rahul799** [comment]
Thankyou @salaheddinek. Eagerly waiting for that feature.

**Comment by salaheddinek** [comment]
Issue fixed in this merge #11
